name = "virol"
main = "cloudflare-worker.js"
compatibility_date = "2024-05-22"

[assets]
directory = "./"
binding = "ASSETS"

# D1 Database — multi-atleta
# Sustituir <DATABASE_ID> por el UUID que da: wrangler d1 create virol-db
[[d1_databases]]
binding = "DB"
database_name = "virol-db"
database_id = "b5446c8b-33ce-4995-b3fd-0ef9504b9c74"

[vars]
STRAVA_CLIENT_ID = "243799"
